P<a,b,z,w> := PolynomialRing(Rationals(),4);
den := a*b + a + b;
s1n := (1+a+b)*den - a*b;
s2n := (a+b+a*b)*den - a*b*(1+a+b);
Rq := 9*s1n^2 - 32*s2n*den;
Sq := 9*s1n^2 - 24*s2n*den;
Q4 := (3*Rq - Sq)/18;
print "ID1 18*Q4 eq 3Rq-Sq:", 18*Q4 eq 3*Rq - Sq;
print "ID2 s1n^2 - Rq eq -8*Q4:", s1n^2 - Rq eq -8*Q4;
print "--- factorization of Q4 ---";
FQ := Factorization(Q4);
print FQ;
sqfree := true;
for t in FQ do if t[2] ge 2 then sqfree := false; end if; end for;
print "Q4 squarefree:", sqfree;
// square tests in QQ(a,b): polynomial square iff all exponents even and lc square
function IsPolySquare(f)
  if f eq 0 then return true; end if;
  FF := Factorization(f);
  for t in FF do if IsOdd(t[2]) then return false; end if; end for;
  lc := LeadingCoefficient(f);
  fl, _ := IsSquare(lc);
  return fl;
end function;
print "--- cover triviality tests (all should be false for nontrivial covers) ---";
print "Q4 square:", IsPolySquare(Q4);
print "Q4*Rq square:", IsPolySquare(Q4*Rq);
print "Q4*Sq square:", IsPolySquare(Q4*Sq);
print "Q4*Rq*Sq square:", IsPolySquare(Q4*Rq*Sq);
print "-2*Q4 square:", IsPolySquare(-2*Q4);
print "-2*Q4*Rq square:", IsPolySquare(-2*Q4*Rq);
print "-2*Q4*Sq square:", IsPolySquare(-2*Q4*Sq);
print "-2*Q4*Rq*Sq square:", IsPolySquare(-2*Q4*Rq*Sq);
print "--- witness values ---";
aa := -51/13; bb := -17/7;
q4v := Evaluate(Q4,[aa,bb,0,0]);
print "Q4 at K-witness:", q4v;
print "Q4 witness negative:", q4v lt 0;
print "--- degeneracy locus Q4 = 0 as plane curve ---";
A2<x,y> := AffineSpace(Rationals(),2);
Q4p := Evaluate(Q4,[x,y,0,0]);
C := Curve(A2, Q4p);
print "C irreducible:", IsIrreducible(C);
if IsIrreducible(C) then
  print "genus of Q4=0:", Genus(C);
end if;
print "--- pullback of Q4=0 to S: dimension and components ---";
I := ideal<P | z^2 - Rq, w^2 - Sq, Q4>;
print "dim of (S meet {Q4=0}):", Dimension(I);
IS := ideal<P | z^2 - Rq, w^2 - Sq>;
print "dim of S:", Dimension(IS);
print "--- primary decomposition of pullback (may take time) ---";
time PD := PrimaryDecomposition(I);
print "number of primary components:", #PD;
for J in PD do
  print "component dim:", Dimension(J);
end for;
print "DONE";
quit;
quit;
